name: contact_picker_example
description: Demonstrates how to use the contact_picker plugin.

dependencies:
  # simple_permissions: ^0.1.5
  simple_permissions:
    path: ../../ened.flutter_simple_permissions
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  contact_picker:
    path: ../

flutter:
  uses-material-design: true
  